# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a, b = 1, 2
print(str(a+b))

3


# 3.Define a list and replicate in three different ways.

In [3]:
listone = [1, 2, 3]
print(f"first way: {listone} \nsecond way: {list(listone)} \nthird way: {listone[:]}")

first way: [1, 2, 3] 
second way: [1, 2, 3] 
third way: [1, 2, 3]


# 4.Define two lists and merge them together.

In [4]:
listone = [1, 2]
listtwo = [3, 4]
listone.extend(listtwo)
print(listone)

[1, 2, 3, 4]


# 5. Get the last element of the list and print it.

In [5]:
listone = [1, 2, 3, 4]
print(listone[-1])

4


# 6.Define a tuple that contains only one element.

In [6]:
a = ('s')
print(a)

s


# 7.Define a three-line long string.

In [7]:
long_string = '''
really
long
string
'''
print(long_string)


really
long
string



# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [8]:
items = (1, 2, 3)
for item in items:
    print(item)

1
2
3


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [9]:
def Mul(num1, num2):
    answer = num1 * num2
    return answer

print(Mul(8, 6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [10]:
import numpy as np
matrixone = np.zeros((5,5))
print(matrixone)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [11]:
matrixone = np.zeros((4,6))
print(matrixone)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [12]:
mat=np.arange(15,)
mat.shape=(3,5)
print(mat.shape)

(3, 5)


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [13]:
A = np.arange(12).reshape(4,3)
B = np.arange(12).reshape(3,4)
result = np.matmul(A, B)
print(result)

[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]
